version: '3'
services:
  docker-postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=todolist_db
    ports:
      - '5432:5432'
    volumes:
      - ./src/main/resources/db/migrations:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready"]
#      interval: 2s
#      timeout: 20s
#      retries: 10

#  todo-backend-app:
#    restart: on-failure
#    build: ./
#    expose:
#      - "8181"
#    ports:
#      - "8181:8181"
#    depends_on:
#      - docker-postgres
#      docker-postgres:
#        condition: service_healthy

#Volume useful to "save" the data between container states
volumes:
  db:
    driver: local